// New questions 66-80 from PDFs — DS, patterns, advanced
export const newQuestions2 = [
  { id: 66, cat: "Patterns", title: "66. Number Pyramid", desc: "Print a number pyramid pattern.",
    c: `#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    for(int i=1;i<=n;i++){for(int j=1;j<=i;j++) printf("%d ",j);printf("\\n");}\n    return 0;\n}`,
    py: `n = int(input("Enter rows: "))\nfor i in range(1, n+1):\n    print(' '.join(str(j) for j in range(1, i+1)))` },

  { id: 67, cat: "Patterns", title: "67. Diamond Pattern", desc: "Print a diamond pattern of stars.",
    c: `#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    for(int i=1;i<=n;i++){for(int j=i;j<n;j++)printf(" ");for(int k=1;k<=(2*i-1);k++)printf("*");printf("\\n");}\n    for(int i=n-1;i>=1;i--){for(int j=i;j<n;j++)printf(" ");for(int k=1;k<=(2*i-1);k++)printf("*");printf("\\n");}\n    return 0;\n}`,
    py: `n = int(input("Enter rows: "))\nfor i in range(1, n+1):\n    print(' '*(n-i) + '*'*(2*i-1))\nfor i in range(n-1, 0, -1):\n    print(' '*(n-i) + '*'*(2*i-1))` },

  { id: 68, cat: "Patterns", title: "68. Hollow Square", desc: "Print a hollow square pattern of stars.",
    c: `#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    for(int i=0;i<n;i++){\n        if(i==0||i==n-1){for(int j=0;j<n;j++)printf("* ");printf("\\n");}\n        else printf("* %*s*\\n",2*(n-2),"");\n    }\n    return 0;\n}`,
    py: `n = int(input("Enter size: "))\nfor i in range(n):\n    if i == 0 or i == n-1:\n        print('* ' * n)\n    else:\n        print('* ' + '  ' * (n-2) + '*')` },

  { id: 69, cat: "Searching & Sorting", title: "69. Find First and Last Position", desc: "Find first and last occurrence of target in sorted array.",
    c: `#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int a[n]; for(int i=0;i<n;i++) scanf("%d",&a[i]);\n    int t; scanf("%d",&t);\n    int first=-1,last=-1;\n    for(int i=0;i<n;i++) if(a[i]==t){if(first==-1)first=i;last=i;}\n    printf("First: %d, Last: %d\\n",first,last);\n    return 0;\n}`,
    py: `n = int(input("Enter number of elements: "))\narr = list(map(int, input("Enter elements: ").split()))\nt = int(input("Enter target: "))\nfirst = next((i for i,x in enumerate(arr) if x==t), -1)\nlast = next((i for i in range(len(arr)-1,-1,-1) if arr[i]==t), -1)\nprint(f"First: {first}, Last: {last}")` },

  { id: 70, cat: "Linked List", title: "70. Reverse Linked List", desc: "Reverse a singly linked list.",
    c: `// Pseudocode for linked list reversal\n#include <stdio.h>\n#include <stdlib.h>\ntypedef struct Node{int data;struct Node*next;}Node;\nNode*reverse(Node*head){\n    Node*prev=NULL,*curr=head,*next;\n    while(curr){next=curr->next;curr->next=prev;prev=curr;curr=next;}\n    return prev;\n}\nint main(){\n    // Demo: create 1->2->3->4->5\n    Node*head=NULL;\n    for(int i=5;i>=1;i--){Node*n=malloc(sizeof(Node));n->data=i;n->next=head;head=n;}\n    head=reverse(head);\n    while(head){printf("%d ",head->data);head=head->next;}\n    return 0;\n}`,
    py: `# Linked list reversal simulation\nclass Node:\n    def __init__(self, val): self.val = val; self.next = None\n\nn = int(input("Enter number of elements: "))\narr = list(map(int, input("Enter elements: ").split()))\nhead = None\nfor v in reversed(arr):\n    node = Node(v); node.next = head; head = node\n\nprev = None\ncurr = head\nwhile curr:\n    nxt = curr.next; curr.next = prev; prev = curr; curr = nxt\nhead = prev\n\nresult = []\nwhile head: result.append(head.val); head = head.next\nprint("Reversed:", result)` },

  { id: 71, cat: "Linked List", title: "71. Add Two Numbers (Linked List)", desc: "Add two numbers represented as linked lists.",
    c: `// Add two numbers as linked lists\n#include <stdio.h>\n#include <stdlib.h>\ntypedef struct Node{int data;struct Node*next;}Node;\nint main(){\n    int n1,n2; scanf("%d%d",&n1,&n2);\n    int a[n1],b[n2];\n    for(int i=0;i<n1;i++) scanf("%d",&a[i]);\n    for(int i=0;i<n2;i++) scanf("%d",&b[i]);\n    int carry=0,i=0,j=0;\n    printf("Sum: ");\n    while(i<n1||j<n2||carry){\n        int s=carry+(i<n1?a[i++]:0)+(j<n2?b[j++]:0);\n        printf("%d ",s%10); carry=s/10;\n    }\n    return 0;\n}`,
    py: `n1 = int(input("Digits in first number: "))\na = list(map(int, input("Enter digits (LSB first): ").split()))\nn2 = int(input("Digits in second number: "))\nb = list(map(int, input("Enter digits (LSB first): ").split()))\ncarry = 0\nresult = []\ni = j = 0\nwhile i < len(a) or j < len(b) or carry:\n    s = carry + (a[i] if i < len(a) else 0) + (b[j] if j < len(b) else 0)\n    result.append(s % 10)\n    carry = s // 10\n    i += 1; j += 1\nprint("Sum digits:", result)` },

  { id: 72, cat: "Stack & Queue", title: "72. Stack Operations", desc: "Implement Push, Pop, Peek on a stack.",
    c: `#include <stdio.h>\n#define MAX 100\nint stack[MAX],top=-1;\nvoid push(int v){if(top<MAX-1)stack[++top]=v;}\nint pop(){return top>=0?stack[top--]:-1;}\nint peek(){return top>=0?stack[top]:-1;}\nint main(){\n    int n; scanf("%d",&n);\n    for(int i=0;i<n;i++){int v;scanf("%d",&v);push(v);}\n    printf("Top: %d\\n",peek());\n    printf("Popped: %d\\n",pop());\n    printf("New Top: %d\\n",peek());\n    return 0;\n}`,
    py: `n = int(input("Enter number of elements to push: "))\nstack = []\nfor v in map(int, input("Enter elements: ").split()):\n    stack.append(v)\n    print(f"Pushed {v}, Stack: {stack}")\nprint("Top:", stack[-1])\npopped = stack.pop()\nprint(f"Popped: {popped}, Stack: {stack}")` },

  { id: 73, cat: "Stack & Queue", title: "73. Queue Operations", desc: "Implement Enqueue, Dequeue on a queue.",
    c: `#include <stdio.h>\n#define MAX 100\nint q[MAX],front=0,rear=-1;\nvoid enqueue(int v){q[++rear]=v;}\nint dequeue(){return front<=rear?q[front++]:-1;}\nint main(){\n    int n; scanf("%d",&n);\n    for(int i=0;i<n;i++){int v;scanf("%d",&v);enqueue(v);}\n    printf("Dequeued: %d\\n",dequeue());\n    printf("Front: %d\\n",q[front]);\n    return 0;\n}`,
    py: `from collections import deque\nn = int(input("Enter number of elements: "))\nqueue = deque()\nfor v in map(int, input("Enter elements: ").split()):\n    queue.append(v)\n    print(f"Enqueued {v}, Queue: {list(queue)}")\nprint("Dequeued:", queue.popleft())\nprint("Queue now:", list(queue))` },

  { id: 74, cat: "Trees", title: "74. Binary Tree Traversals", desc: "Perform Inorder, Preorder, and Postorder traversal.",
    c: `#include <stdio.h>\n#include <stdlib.h>\ntypedef struct N{int d;struct N*l,*r;}N;\nN*newN(int d){N*n=malloc(sizeof(N));n->d=d;n->l=n->r=NULL;return n;}\nvoid inorder(N*r){if(r){inorder(r->l);printf("%d ",r->d);inorder(r->r);}}\nvoid preorder(N*r){if(r){printf("%d ",r->d);preorder(r->l);preorder(r->r);}}\nvoid postorder(N*r){if(r){postorder(r->l);postorder(r->r);printf("%d ",r->d);}}\nint main(){\n    N*root=newN(1);root->l=newN(2);root->r=newN(3);root->l->l=newN(4);root->l->r=newN(5);\n    printf("Inorder: ");inorder(root);printf("\\nPreorder: ");preorder(root);printf("\\nPostorder: ");postorder(root);\n    return 0;\n}`,
    py: `class Node:\n    def __init__(self, val): self.val=val; self.left=None; self.right=None\n\ndef inorder(r):\n    return inorder(r.left)+[r.val]+inorder(r.right) if r else []\ndef preorder(r):\n    return [r.val]+preorder(r.left)+preorder(r.right) if r else []\ndef postorder(r):\n    return postorder(r.left)+postorder(r.right)+[r.val] if r else []\n\nroot=Node(1);root.left=Node(2);root.right=Node(3)\nroot.left.left=Node(4);root.left.right=Node(5)\nprint("Inorder:", inorder(root))\nprint("Preorder:", preorder(root))\nprint("Postorder:", postorder(root))` },

  { id: 75, cat: "Trees", title: "75. Height of Binary Tree", desc: "Find the height of a binary tree.",
    c: `#include <stdio.h>\n#include <stdlib.h>\ntypedef struct N{int d;struct N*l,*r;}N;\nN*newN(int d){N*n=malloc(sizeof(N));n->d=d;n->l=n->r=NULL;return n;}\nint height(N*r){if(!r)return 0;int lh=height(r->l),rh=height(r->r);return 1+(lh>rh?lh:rh);}\nint main(){\n    N*root=newN(1);root->l=newN(2);root->r=newN(3);root->l->l=newN(4);root->l->l->l=newN(5);\n    printf("Height: %d\\n",height(root));\n    return 0;\n}`,
    py: `class Node:\n    def __init__(self, val): self.val=val; self.left=None; self.right=None\n\ndef height(root):\n    if not root: return 0\n    return 1 + max(height(root.left), height(root.right))\n\nroot=Node(1);root.left=Node(2);root.right=Node(3)\nroot.left.left=Node(4);root.left.left.left=Node(5)\nprint("Height:", height(root))` },

  { id: 76, cat: "Graphs", title: "76. DFS (Depth First Search)", desc: "Traverse a graph using Depth First Search.",
    c: `#include <stdio.h>\nint adj[10][10],vis[10],n;\nvoid dfs(int v){vis[v]=1;printf("%d ",v);for(int i=0;i<n;i++)if(adj[v][i]&&!vis[i])dfs(i);}\nint main(){\n    int e; scanf("%d%d",&n,&e);\n    for(int i=0;i<e;i++){int u,v;scanf("%d%d",&u,&v);adj[u][v]=adj[v][u]=1;}\n    printf("DFS: ");dfs(0);\n    return 0;\n}`,
    py: `n = int(input("Number of nodes: "))\ne = int(input("Number of edges: "))\ngraph = {i: [] for i in range(n)}\nfor _ in range(e):\n    u, v = map(int, input("Edge (u v): ").split())\n    graph[u].append(v); graph[v].append(u)\n\ndef dfs(node, visited):\n    visited.add(node)\n    print(node, end=' ')\n    for nb in graph[node]:\n        if nb not in visited: dfs(nb, visited)\n\nprint("DFS:", end=' ')\ndfs(0, set())` },

  { id: 77, cat: "Graphs", title: "77. BFS (Breadth First Search)", desc: "Traverse a graph using Breadth First Search.",
    c: `#include <stdio.h>\nint adj[10][10],vis[10],n;\nint q[100],front=0,rear=-1;\nint main(){\n    int e; scanf("%d%d",&n,&e);\n    for(int i=0;i<e;i++){int u,v;scanf("%d%d",&u,&v);adj[u][v]=adj[v][u]=1;}\n    vis[0]=1;q[++rear]=0;\n    printf("BFS: ");\n    while(front<=rear){\n        int v=q[front++];printf("%d ",v);\n        for(int i=0;i<n;i++)if(adj[v][i]&&!vis[i]){vis[i]=1;q[++rear]=i;}\n    }\n    return 0;\n}`,
    py: `from collections import deque\nn = int(input("Number of nodes: "))\ne = int(input("Number of edges: "))\ngraph = {i: [] for i in range(n)}\nfor _ in range(e):\n    u, v = map(int, input("Edge (u v): ").split())\n    graph[u].append(v); graph[v].append(u)\n\ndef bfs(start):\n    visited = {start}\n    queue = deque([start])\n    while queue:\n        node = queue.popleft()\n        print(node, end=' ')\n        for nb in graph[node]:\n            if nb not in visited:\n                visited.add(nb); queue.append(nb)\n\nprint("BFS:", end=' ')\nbfs(0)` },

  { id: 78, cat: "Advanced", title: "78. Unique Paths (Grid)", desc: "Count unique paths from top-left to bottom-right of a grid.",
    c: `#include <stdio.h>\nint main() {\n    int m,n; scanf("%d%d",&m,&n);\n    int dp[m][n];\n    for(int i=0;i<m;i++) for(int j=0;j<n;j++){\n        if(i==0||j==0) dp[i][j]=1;\n        else dp[i][j]=dp[i-1][j]+dp[i][j-1];\n    }\n    printf("Paths: %d\\n",dp[m-1][n-1]);\n    return 0;\n}`,
    py: `m = int(input("Enter rows: "))\nn = int(input("Enter columns: "))\ndp = [[1]*n for _ in range(m)]\nfor i in range(1, m):\n    for j in range(1, n):\n        dp[i][j] = dp[i-1][j] + dp[i][j-1]\nprint("Unique Paths:", dp[m-1][n-1])` },

  { id: 79, cat: "Advanced", title: "79. Jump Game", desc: "Determine minimum jumps to reach end of array.",
    c: `#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int a[n]; for(int i=0;i<n;i++) scanf("%d",&a[i]);\n    int jumps=0,end=0,far=0;\n    for(int i=0;i<n-1;i++){\n        if(i+a[i]>far) far=i+a[i];\n        if(i==end){jumps++;end=far;}\n    }\n    printf("Min Jumps: %d\\n",jumps);\n    return 0;\n}`,
    py: `n = int(input("Enter number of elements: "))\narr = list(map(int, input("Enter elements: ").split()))\njumps = current_end = farthest = 0\nfor i in range(n - 1):\n    farthest = max(farthest, i + arr[i])\n    if i == current_end:\n        jumps += 1\n        current_end = farthest\nprint("Min Jumps:", jumps)` },

  { id: 80, cat: "Searching & Sorting", title: "80. Count Inversions", desc: "Count pairs where a[i] > a[j] and i < j.",
    c: `#include <stdio.h>\nint main() {\n    int n; scanf("%d",&n);\n    int a[n]; for(int i=0;i<n;i++) scanf("%d",&a[i]);\n    int cnt=0;\n    for(int i=0;i<n;i++) for(int j=i+1;j<n;j++) if(a[i]>a[j]) cnt++;\n    printf("Inversions: %d\\n",cnt);\n    return 0;\n}`,
    py: `n = int(input("Enter number of elements: "))\narr = list(map(int, input("Enter elements: ").split()))\ncount = sum(1 for i in range(n) for j in range(i+1, n) if arr[i] > arr[j])\nprint("Inversions:", count)` },
];
